Repository cc65/cc65, pull requests merged in 2025-04, with the labels that each got.

#2625 Added doc and some refs #2613
  doc/apple2.sgml
  doc/apple2enh.sgml
  doc/atari.sgml
  doc/chrcvt65.sgml
  doc/funcref.sgml
Labels: enhancement, documentation

#2626 Fix a typo in g_typeadjust()
  src/cc65/codegen.c
Labels: bug, cc65

#2630 Fix documentation about unnamed labels using an `@`.
  doc/ca65.sgml
Labels: bug, documentation
